name = "LibCEED2LFAToolkit"
uuid = "61e60817-c62c-46c6-8fbb-8410bece4e13"
authors = ["Jeremy L Thompson <jeremy@jeremylt.org>"]
version = "0.1.0"

[deps]
LFAToolkit = "3f92b583-c0aa-4596-8bdf-f02f6c0a52df"
LibCEED = "2cd74e05-b976-4426-91fa-5f1011f8952b"

[compat]
LFAToolkit = "0.6.0"
LibCEED = "0.1.2, 0.2"
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "LinearAlgebra"]
